version: '3.8'

services:
  tableau-to-pbi:
    build: .
    container_name: tableau-to-pbi-converter
    volumes:
      # Mount input directory
      - ./input:/app/input:ro
      # Mount output directory
      - ./output:/app/output
      # Mount examples
      - ./examples:/app/examples:ro
    environment:
      - DISPLAY=${DISPLAY}
      - PYTHONPATH=/app/src
    stdin_open: true
    tty: true
    